myshoppingapp/myshoppingapp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls'))
]

myshoppingapp/shop/urls.py
from django.urls import path
from . import views
app_name = 'shop'
urlpatterns = [
    path('',views.index, name='index'),
    path('<int:item_id>/',views.detail,name='detail'),
    path('shoes',views.shoes, name='shoes'),
    path('clothes',views.clothes, name='clothes')
]

myshoppingapp/shop/models.py
from django.db import models

# Create your models here.

class Item(models.Model):
    def __str__(self) -> str:
        return self.item_name
    item_name = models.CharField(max_length=150)
    item_descp = models.CharField(max_length=150)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500,default="https://i.ytimg.com/vi/qnEjanlGXok/maxresdefault.jpg")
    

myshoppingapp/shop/views.py
from django.shortcuts import render
from django.http import HttpResponse
from shop.models import Item
from django.template import loader
# Create your views here.

# def index (request):
#     item_list = Item.objects.all()
#     template = loader.get_template('shop/index.html')
#     context = {
#         'item_list': item_list,
#     }
#     return HttpResponse(template.render(context,request))
def index (request):
    item_list = Item.objects.all()
    context = {
        'item_list': item_list,
    }
    return render(request, 'shop/index.html', context)
def shoes (request):
    return HttpResponse("This will be the shoes page!")
def clothes (request):
    return HttpResponse("This will be the clothes page!")
def detail (request, item_id):
    item = Item.objects.get(pk=item_id)
    context= {
        'item':item,
    }
    return render(request,'shop/detail.html',context)

myshoppingapp/shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script> 
    <link rel="stylesheet" href="{% static 'shop/styles.css' %}">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark navbar-expand">
        <a href="#" class="navbar-brand">Shop App</a>
        <div class="navbar-nav ms-auto">
            <a class="nav-item nav-link" href="#">View Item</a>
            <a class="nav-item nav-link" href="#">Add Item</a>
            <a class="nav-item nav-link" href="#">Remove Item</a>

        </div>

    </nav>
{% block content %}
{% endblock  %}
</body>
</html>

myshoppingapp/shop/templates/shop/detail.html
{% extends "shop/base.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img class="img-card" height="300px" src="{{item.item_image}}">
        </div>
        <div class="col-md-6">
            <h1>{{item.item_name}}</h1>
            <h2>{{item.item_descp}}</h2>
            <h3>kes {{item.item_price}}</h3> 
        </div>
    </div>
</div>

{% endblock  %}

myshoppingapp/shop/templates/shop/index.html
{% extends "shop/base.html" %}
{% block content %}

{% for item in item_list %}
   <div class="row">
        <div class="col-md-3 offset-md-2" "image-container">
            <img class="img-card" height="150px" src="{{item.item_image}}">

        </div>
        <div class="col-md-4">
            <h3>{{ item.item_name }}</h3>
            <h5>{{ item.item_descp }}</h5>
            <h6>kes {{ item.item_price }}</h6>
        </div>
        <div class="col-md-2">
            <a href="{% url "shop:detail" item.id %}" class="btn btn-success">Details</a>
        </div>

   </div> 
{% endfor %}
{% endblock  %}
<ul>
    <a href="/shop/{{item.id}}">{{item.id}}.  {{item.item_name}}</a>
</ul>